### ISSUE TITLE
Variable allocated on heap instead of stack

### ISSUE THREAD

**Issue by ickule** [ickule/yagolic#11]

**Comment by ickule** [comment]
Made a solution based on latest developments from #31 to compare things and decide between heap and stack allocation for the board.

**Comment by kaoliiny** [comment]
Please explain me the main differences between heap and stack allocation before it can be approved

**Comment by ickule** [comment]
Feels like you should be the one explaining here but here is my take on it:

- Heap allocation uses the dynamic memory, providing a lifetime that goes beyond the the scope of the function but requires manual management and is slower to allocate and access.
- Stack allocation is automatically managed which means safer, faster access time and allocation time at the expense of lifetime which is limited to the scope of the function.

Since we do not know the size of our board before compile time, the only two options I see are:

1. We allocate a big chunk from stack and check user input to be within bounds
2. We allocate exactly what we need from the heap

And I would prefer option 2, I think it makes for more readable code and smaller footprint program and since we have a simple program, manual management will be manageable.

I don't mean it to be a false dilemma however, so I welcome any further solutions I may not have thought about.

**Comment by kaoliiny** [comment]
Additionally l would go a bit more into details:
1. For example in Linux systems dynamic memory allocation works through system calls and allocation itself happens by kernel. So you can understand how much time consuming it actually is.
So it inappropriate to use for allocating little (frequent) amount of memory. 
3. Dynamic memory doesn't allocate exact amount of memory you asking for. It also returns some system info about allocated memory and aligns it.
4. Frequent use of malloc cause memory fragmentation
5. As well  it may cause leaks and other problems.

As the mentioned thing not the actual use case malloc currently can be left. 🤔😉
