### ISSUE TITLE
Change coordonate system to be slightly clearer

### ISSUE THREAD

**Issue by ickule** [ickule/yagolic#36]
i -> x
j -> y
This will be a bit clearer across the board.
(pun intended).

**Comment by ickule** [comment]
This was initially done in https://github.com/ickule/yagolic/pull/31 but was moved since it is an unrelated change.

**Comment by kaoliiny** [comment]
This issue does not bring any value

**Comment by ickule** [comment]
That's fair actually.
I changed stuff around in and kept the "i" and "j".
