### ISSUE TITLE
Use correct data types

### ISSUE THREAD

**Issue by kaoliiny** [ickule/yagolic#51]
Acceptance criterias: 
1. Whenever it's needed use 'unsigned' instead of 'int'.
2. Delete useless zero checks (x < 0)

**Comment by ickule** [comment]
How about we use `stdbool.h` for the cells as well?

**Comment by kaoliiny** [comment]
Actually no sense. It has same amount of space as uint8_t (short) anyway.

**Comment by ickule** [comment]
I believe (u)int8_t are char and (u)int16_t are short.
In any case, allocating an array from heap uses the same amount of space regardless of the integer type used (`char`, `short`, `int` or `long`). At least in my limited testing with `sizeof`.
I'll just switch the cells to `unsigned char*` for the sake of completeness.
Is that reasonable ?

I think we can even switch `rows` and `cols` to `unsigned short`, I hardly see a user needing more that 65535 rows or cols.
